# Anywhy Flake configuration
#
# BLE sleep and soft power-off for battery saving.
# Experimental BLE features required for reliable split wireless operation on XIAO BLE.
# Adapted from anywhy-io/flake-firmware (MIT License).
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_PM_SOFT_OFF=y
